-- Ultrix Leave Portal — run in Supabase SQL editor (once)

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'manager', 'hr')) DEFAULT 'user',
  manager_id INTEGER REFERENCES users(id),
  employee_number TEXT UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  casual DOUBLE PRECISION NOT NULL DEFAULT 0,
  earned DOUBLE PRECISION NOT NULL DEFAULT 0,
  sick DOUBLE PRECISION NOT NULL DEFAULT 0,
  compensation DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick', 'compensation', 'wfh')),
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  days DOUBLE PRECISION NOT NULL,
  session TEXT NOT NULL CHECK (session IN ('full', 'morning', 'afternoon')) DEFAULT 'full',
  reason TEXT,
  status TEXT NOT NULL CHECK (status IN (
    'pending_manager', 'pending_hr', 'approved', 'rejected', 'cancelled'
  )) DEFAULT 'pending_manager',
  manager_note TEXT,
  manager_id INTEGER REFERENCES users(id),
  manager_reviewed_at TEXT,
  hr_note TEXT,
  hr_id INTEGER REFERENCES users(id),
  hr_reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS balance_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick', 'compensation')),
  amount DOUBLE PRECISION NOT NULL,
  note TEXT,
  credited_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_id INTEGER REFERENCES leave_requests(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  manager_id INTEGER NOT NULL REFERENCES users(id),
  score DOUBLE PRECISION NOT NULL CHECK (score >= 1 AND score <= 10),
  feedback TEXT NOT NULL,
  period_label TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_ratings_user ON employee_ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_manager ON employee_ratings(manager_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_created ON employee_ratings(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_ratings_user_period
  ON employee_ratings(user_id, period_label)
  WHERE period_label IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_employee_number
  ON users(employee_number)
  WHERE employee_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS employee_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  profile_photo TEXT,
  date_of_birth TEXT,
  gender TEXT,
  personal_email TEXT,
  personal_mobile TEXT,
  address TEXT,
  emergency_contact TEXT,
  nationality TEXT,
  marital_status TEXT,
  date_of_joining TEXT,
  employment_type TEXT,
  department TEXT,
  designation TEXT,
  job_level TEXT,
  location TEXT,
  work_mode TEXT,
  employment_status TEXT NOT NULL DEFAULT 'active',
  probation_period TEXT,
  confirmation_date TEXT,
  employee_category TEXT,
  laptop_desktop_assigned TEXT,
  asset_id TEXT,
  company_mobile TEXT,
  access_card TEXT,
  equipment_issue_date TEXT,
  equipment_return_date TEXT,
  software_access_provisioning TEXT,
  company_email_account TEXT,
  basic_salary DOUBLE PRECISION,
  hra DOUBLE PRECISION,
  allowances DOUBLE PRECISION,
  variable_pay DOUBLE PRECISION,
  bonuses DOUBLE PRECISION,
  deductions DOUBLE PRECISION,
  pf_epf_details TEXT,
  professional_tax DOUBLE PRECISION,
  tds DOUBLE PRECISION,
  net_salary DOUBLE PRECISION,
  salary_history TEXT,
  payslips TEXT,
  bank_account_details TEXT,
  stipend DOUBLE PRECISION,
  fixed_pay DOUBLE PRECISION,
  joining_bonus DOUBLE PRECISION,
  retention_bonus DOUBLE PRECISION,
  esops TEXT,
  bonus_amount DOUBLE PRECISION,
  bonus_frequency TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_profiles_user ON employee_profiles(user_id);

CREATE TABLE IF NOT EXISTS employee_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset_category TEXT NOT NULL DEFAULT 'other',
  device_assigned TEXT,
  asset_id TEXT,
  mobile_number TEXT,
  access_card TEXT,
  issue_date TEXT,
  return_date TEXT,
  software_access TEXT,
  company_email TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_assets_user ON employee_assets(user_id);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  invoice_date TEXT NOT NULL,
  billing_period TEXT NOT NULL,
  consultant TEXT NOT NULL,
  total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  data_json TEXT NOT NULL,
  pdf_data TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_invoices_billing_period ON invoices(billing_period);
CREATE INDEX IF NOT EXISTS idx_invoices_user ON invoices(user_id);

CREATE TABLE IF NOT EXISTS mandatory_leaves (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  note TEXT,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_mandatory_leaves_dates ON mandatory_leaves(start_date, end_date);
