-- Ultrix Leave Portal — run in Supabase SQL editor (once)

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'manager', 'hr')) DEFAULT 'user',
  manager_id INTEGER REFERENCES users(id),
  employee_number TEXT UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  casual DOUBLE PRECISION NOT NULL DEFAULT 0,
  earned DOUBLE PRECISION NOT NULL DEFAULT 0,
  sick DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick', 'wfh')),
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  days DOUBLE PRECISION NOT NULL,
  session TEXT NOT NULL CHECK (session IN ('full', 'morning', 'afternoon')) DEFAULT 'full',
  reason TEXT,
  status TEXT NOT NULL CHECK (status IN (
    'pending_manager', 'pending_hr', 'approved', 'rejected', 'cancelled'
  )) DEFAULT 'pending_manager',
  manager_note TEXT,
  manager_id INTEGER REFERENCES users(id),
  manager_reviewed_at TEXT,
  hr_note TEXT,
  hr_id INTEGER REFERENCES users(id),
  hr_reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS balance_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick')),
  amount DOUBLE PRECISION NOT NULL,
  note TEXT,
  credited_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_id INTEGER REFERENCES leave_requests(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  manager_id INTEGER NOT NULL REFERENCES users(id),
  score DOUBLE PRECISION NOT NULL CHECK (score >= 1 AND score <= 10),
  feedback TEXT NOT NULL,
  period_label TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_ratings_user ON employee_ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_manager ON employee_ratings(manager_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_created ON employee_ratings(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_ratings_user_period
  ON employee_ratings(user_id, period_label)
  WHERE period_label IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_employee_number
  ON users(employee_number)
  WHERE employee_number IS NOT NULL;
