-- Ultrix Leave Portal — run in Supabase SQL editor (once)

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'manager', 'hr')) DEFAULT 'user',
  manager_id INTEGER REFERENCES users(id),
  employee_number TEXT UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  casual DOUBLE PRECISION NOT NULL DEFAULT 0,
  earned DOUBLE PRECISION NOT NULL DEFAULT 0,
  sick DOUBLE PRECISION NOT NULL DEFAULT 0,
  restricted DOUBLE PRECISION NOT NULL DEFAULT 2,
  celebration DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick', 'wfh', 'restricted', 'celebration')),
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  days DOUBLE PRECISION NOT NULL,
  session TEXT NOT NULL CHECK (session IN ('full', 'morning', 'afternoon')) DEFAULT 'full',
  reason TEXT,
  status TEXT NOT NULL CHECK (status IN (
    'pending_manager', 'pending_hr', 'approved', 'rejected', 'cancelled'
  )) DEFAULT 'pending_manager',
  manager_note TEXT,
  manager_id INTEGER REFERENCES users(id),
  manager_reviewed_at TEXT,
  hr_note TEXT,
  hr_id INTEGER REFERENCES users(id),
  hr_reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS balance_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL CHECK (leave_type IN ('casual', 'earned', 'sick', 'restricted', 'celebration')),
  amount DOUBLE PRECISION NOT NULL,
  note TEXT,
  credited_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_id INTEGER REFERENCES leave_requests(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_ratings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  manager_id INTEGER NOT NULL REFERENCES users(id),
  score DOUBLE PRECISION NOT NULL CHECK (score >= 1 AND score <= 10),
  feedback TEXT NOT NULL,
  period_label TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_ratings_user ON employee_ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_manager ON employee_ratings(manager_id);
CREATE INDEX IF NOT EXISTS idx_employee_ratings_created ON employee_ratings(created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_ratings_user_period
  ON employee_ratings(user_id, period_label)
  WHERE period_label IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_employee_number
  ON users(employee_number)
  WHERE employee_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS employee_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  profile_photo TEXT,
  date_of_birth TEXT,
  gender TEXT,
  personal_email TEXT,
  personal_mobile TEXT,
  address TEXT,
  emergency_contact TEXT,
  nationality TEXT,
  marital_status TEXT,
  date_of_joining TEXT,
  employment_type TEXT,
  department TEXT,
  designation TEXT,
  job_level TEXT,
  location TEXT,
  work_mode TEXT,
  employment_status TEXT NOT NULL DEFAULT 'active',
  probation_period TEXT,
  confirmation_date TEXT,
  employee_category TEXT,
  laptop_desktop_assigned TEXT,
  asset_id TEXT,
  company_mobile TEXT,
  access_card TEXT,
  equipment_issue_date TEXT,
  equipment_return_date TEXT,
  software_access_provisioning TEXT,
  company_email_account TEXT,
  basic_salary DOUBLE PRECISION,
  hra DOUBLE PRECISION,
  allowances DOUBLE PRECISION,
  variable_pay DOUBLE PRECISION,
  bonuses DOUBLE PRECISION,
  deductions DOUBLE PRECISION,
  pf_epf_details TEXT,
  professional_tax DOUBLE PRECISION,
  tds DOUBLE PRECISION,
  net_salary DOUBLE PRECISION,
  salary_history TEXT,
  payslips TEXT,
  bank_account_details TEXT,
  stipend DOUBLE PRECISION,
  fixed_pay DOUBLE PRECISION,
  joining_bonus DOUBLE PRECISION,
  retention_bonus DOUBLE PRECISION,
  esops TEXT,
  bonus_amount DOUBLE PRECISION,
  bonus_frequency TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_profiles_user ON employee_profiles(user_id);

CREATE TABLE IF NOT EXISTS employee_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset_category TEXT NOT NULL DEFAULT 'other',
  device_assigned TEXT,
  asset_id TEXT,
  mobile_number TEXT,
  access_card TEXT,
  issue_date TEXT,
  return_date TEXT,
  software_access TEXT,
  company_email TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_employee_assets_user ON employee_assets(user_id);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  invoice_date TEXT NOT NULL,
  billing_period TEXT NOT NULL,
  consultant TEXT NOT NULL,
  total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  data_json TEXT NOT NULL,
  pdf_data TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_invoices_billing_period ON invoices(billing_period);
CREATE INDEX IF NOT EXISTS idx_invoices_user ON invoices(user_id);

CREATE TABLE IF NOT EXISTS mandatory_leaves (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  note TEXT,
  holiday_type TEXT NOT NULL DEFAULT 'general',
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_mandatory_leaves_dates ON mandatory_leaves(start_date, end_date);

CREATE TABLE IF NOT EXISTS feed_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK(category IN ('celebration', 'milestone', 'announcement', 'casual', 'poll')),
  content TEXT NOT NULL,
  image_data TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_feed_posts_created ON feed_posts(created_at);
CREATE INDEX IF NOT EXISTS idx_feed_posts_category ON feed_posts(category);

CREATE TABLE IF NOT EXISTS feed_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES feed_posts(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_feed_comments_post ON feed_comments(post_id, created_at);

CREATE TABLE IF NOT EXISTS feed_reactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER REFERENCES feed_posts(id) ON DELETE CASCADE,
  comment_id INTEGER REFERENCES feed_comments(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (
    (post_id IS NOT NULL AND comment_id IS NULL) OR
    (post_id IS NULL AND comment_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_feed_reactions_post
  ON feed_reactions(post_id, user_id, emoji) WHERE post_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_feed_reactions_comment
  ON feed_reactions(comment_id, user_id, emoji) WHERE comment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS feed_polls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL UNIQUE REFERENCES feed_posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feed_poll_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES feed_polls(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_feed_poll_options_poll ON feed_poll_options(poll_id);

CREATE TABLE IF NOT EXISTS feed_poll_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES feed_polls(id) ON DELETE CASCADE,
  option_id INTEGER NOT NULL REFERENCES feed_poll_options(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_feed_poll_votes_user ON feed_poll_votes(poll_id, user_id);
CREATE INDEX IF NOT EXISTS idx_feed_poll_votes_option ON feed_poll_votes(option_id);

CREATE TABLE IF NOT EXISTS punch_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  device_user_code TEXT NOT NULL,
  punched_at TEXT NOT NULL,
  punch_date TEXT NOT NULL,
  serial_number TEXT NOT NULL DEFAULT '',
  direction TEXT NOT NULL DEFAULT '',
  raw_line TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_punch_logs_unique
  ON punch_logs(device_user_code, punched_at, serial_number);
CREATE INDEX IF NOT EXISTS idx_punch_logs_date ON punch_logs(punch_date, punched_at);
CREATE INDEX IF NOT EXISTS idx_punch_logs_user ON punch_logs(user_id, punch_date);

CREATE TABLE IF NOT EXISTS reimbursement_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_code TEXT NOT NULL UNIQUE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('travel', 'meal', 'office_supplies', 'internet', 'other')),
  expense_date TEXT NOT NULL,
  description TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  payment_mode TEXT NOT NULL CHECK (payment_mode IN ('self', 'company')) DEFAULT 'self',
  currency TEXT NOT NULL DEFAULT 'INR',
  notes TEXT,
  receipt_data TEXT,
  receipt_name TEXT,
  receipt_mime TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'reimbursed', 'cancelled')) DEFAULT 'pending',
  hr_note TEXT,
  hr_id INTEGER REFERENCES users(id),
  hr_reviewed_at TEXT,
  reimbursed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_reimbursements_user ON reimbursement_requests(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reimbursements_status ON reimbursement_requests(status, created_at);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS reimbursement_id INTEGER REFERENCES reimbursement_requests(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS attendance_regularizations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  punch_date TEXT NOT NULL,
  current_punch_in TEXT,
  current_punch_out TEXT,
  current_work_minutes DOUBLE PRECISION,
  proposed_punch_in TEXT NOT NULL,
  proposed_punch_out TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')) DEFAULT 'pending',
  hr_note TEXT,
  hr_id INTEGER REFERENCES users(id),
  hr_reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_att_reg_user_date ON attendance_regularizations(user_id, punch_date);
CREATE INDEX IF NOT EXISTS idx_att_reg_status ON attendance_regularizations(status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_att_reg_pending_day
  ON attendance_regularizations(user_id, punch_date) WHERE status = 'pending';
CREATE UNIQUE INDEX IF NOT EXISTS idx_att_reg_approved_day
  ON attendance_regularizations(user_id, punch_date) WHERE status = 'approved';
